### ISSUE TITLE
Convert Documents to Google Docs

### ISSUE THREAD

**Issue by LichOubliette** [LichOubliette/Horizon#3]

**Comment by bbk1524** [comment]
I have:
- Copied all documents except Slideshow Template into a GDrive friendly format.
    - On the text documents, headers and footers are not preserved, so I added a Revision Date YYYY-MM-DD subtitle.
- Moved all non-Gdrive friendly documents except the Slideshow Template into a new folder: *Non_GDrive_Copies*
- Began a Slideshow Template with Google Slides with a temporary logo: *Temp_Logo.png*

**Comment by bbk1524** [comment]
Waiting for you to close issue or comment with changes.

**Comment by LichOubliette** [comment]
-Headers and footers are preserved, I have no clue what you are talking about.
-Why do we need the Non-GDrive_Copies folder again?
-I'm starting to think we should just cut the slideshow template for now. Google docs doesn't do slideshows very well and hopefully we won't need them for a while anyway.

**Comment by LichOubliette** [comment]
Changed document font-family to Arial, a sans serif font, to make it easier on the eyes.

**Comment by bbk1524** [comment]
- Headers and footers are the parts above and below the content. The page number is a part of a header or footer, for example. When I look at the docs, I don't see headers or footers like I do in the Word versions
- I don't think we do need the Non_GDrive_Copies folder. I left it there in case you didn't like the GDocs version I made. I'm fine with getting rid of it if you are.
- I'm all for not doing slideshows until we have to.
