### ISSUE TITLE
Flesh Out CSD

### ISSUE THREAD

**Issue by LichOubliette** [LichOubliette/Horizon#4]

**Comment by bbk1524** [comment]
It looks workable. I'm moving more to PEP8 styles:
function_name() vis functionName(), but not a problem. I added an "If in doubt, comment" line to the Comment section.

**Comment by LichOubliette** [comment]
Can you explain why you feel underscores are better than camel case?

**Comment by bbk1524** [comment]
It boils down to "that's what Python uses" and I've come around to the idea that it looks a tad cleaner. Additionally, STL uses it (`v.push_back()` not `v.pushBack()`). This is solely a personal preference though, and I have no real issues with camelCase function names.

**Comment by LichOubliette** [comment]
I agree that it's more readable, but for multi-word function names it can really blow up the length.
