### ISSUE TITLE
Implement Graphics System

### ISSUE THREAD

**Issue by LichOubliette** [LichOubliette/Horizon#8]

**Comment by LichOubliette** [comment]
So, I'm going to do this incrementally following Casey Muratori's example. I will make commits as I follow the lazyfoo SDL2 tutorials and build up classes as I go. We will figure out the architecture once we have displaying working.

**Comment by bbk1524** [comment]
Ok. Also read http://mollyrocket.com/casey/stream_0019.html for his views on compression-oriented programming. Before we get too far though, shouldn't we have mock-ups of the screens? I looked for a game description in GDrive, and I couldn't find one. Having a few examples of possible screens in our game will give us a much better idea of what to architect.
http://rivermanmedia.com/object-oriented-game-programming-the-gui-stack/ has an interesting approach too.

**Comment by LichOubliette** [comment]
Ben...what do you think the comments of the individual issues are for? You are so beyond off topic.

**Comment by LichOubliette** [comment]
The base functionality has been baked in. We just need to smooth it out now.

**Comment by LichOubliette** [comment]
One of the things we need to decide on is how to use the draw_image function(s). Do we want one monolith function that takes all appropriate parameters or several options that have fewer parameters for common configurations? If several functions, should those functions call each other or does each need drawing code?

**Comment by LichOubliette** [comment]
Another thought. I think the graphics system should hold on to all the drawable objects. Should outside objects be able to fetch these objects and use their interfaces or should we just let them query the data they need. For example: if I want the height of the image, should I get the image from the graphics system and get it's height or just ask the graphics system for the height directly?
